name: aiml25-ma2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - scikit-learn
  - matplotlib
  - pandas
  - python-decouple
  - pylance
  - fastparquet
  - huggingface_hub
  - jupyter
  - ipywidgets
  - pre-commit
  - transformers
  - datasets
  - pytorch
  - pip:
    - ibm-watsonx-ai==1.2.9
